/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Color;

/**
 *
 * @author 18PROGB0026
 */
public class Actividad extends javax.swing.JFrame {

    /**
     * Creates new form Actividad
     */
    public Actividad() {
        initComponents();
        this.getContentPane().setBackground(Color.orange);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbP1r1 = new javax.swing.JRadioButton();
        rbP1r2 = new javax.swing.JRadioButton();
        rbP1r3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPregunta1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPregunta2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPregunta3 = new javax.swing.JTextArea();
        rbP2r1 = new javax.swing.JRadioButton();
        rbP2r2 = new javax.swing.JRadioButton();
        rbP2r3 = new javax.swing.JRadioButton();
        btnRegresar = new javax.swing.JButton();
        lblImagen3 = new javax.swing.JLabel();
        lblRes = new javax.swing.JLabel();
        lblRes2 = new javax.swing.JLabel();
        lblRes3 = new javax.swing.JLabel();
        rbP3r1 = new javax.swing.JRadioButton();
        rbP3r2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Actividad");
        setResizable(false);

        rbP1r1.setText("ATP");
        rbP1r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbP1r1ActionPerformed(evt);
            }
        });

        rbP1r2.setText("H2O");
        rbP1r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbP1r2ActionPerformed(evt);
            }
        });

        rbP1r3.setText("CO2");
        rbP1r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbP1r3ActionPerformed(evt);
            }
        });

        txtPregunta1.setEditable(false);
        txtPregunta1.setColumns(25);
        txtPregunta1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtPregunta1.setLineWrap(true);
        txtPregunta1.setRows(1);
        txtPregunta1.setTabSize(2);
        txtPregunta1.setText("El principal producto de la respiración celular es");
        txtPregunta1.setWrapStyleWord(true);
        txtPregunta1.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtPregunta1);

        txtPregunta2.setEditable(false);
        txtPregunta2.setColumns(20);
        txtPregunta2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtPregunta2.setLineWrap(true);
        txtPregunta2.setRows(2);
        txtPregunta2.setText("En esta reaccion el NADH se oxida y el acido priruvico se reduce transformandose en ");
        txtPregunta2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtPregunta2);

        txtPregunta3.setColumns(20);
        txtPregunta3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtPregunta3.setLineWrap(true);
        txtPregunta3.setRows(1);
        txtPregunta3.setText("Es la respiracion celular en la cual no se utiliza el oxigeno");
        txtPregunta3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtPregunta3);

        rbP2r1.setText("Acido lactico");
        rbP2r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbP2r1ActionPerformed(evt);
            }
        });

        rbP2r2.setText("Acido priruvico");
        rbP2r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbP2r2ActionPerformed(evt);
            }
        });

        rbP2r3.setText("Acido suslfurico");
        rbP2r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbP2r3ActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblImagen3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen5.jpg"))); // NOI18N

        lblRes.setBackground(new java.awt.Color(153, 153, 153));
        lblRes.setForeground(new java.awt.Color(0, 102, 102));

        lblRes2.setForeground(new java.awt.Color(0, 102, 102));

        lblRes3.setForeground(new java.awt.Color(0, 102, 102));

        rbP3r1.setText("Anaerobica");
        rbP3r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbP3r1ActionPerformed(evt);
            }
        });

        rbP3r2.setText("Aerobia");
        rbP3r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbP3r2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbP2r1)
                                .addGap(18, 18, 18)
                                .addComponent(rbP2r2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbP2r3)
                                .addGap(18, 18, 18)
                                .addComponent(lblRes2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbP1r1)
                                    .addGap(62, 62, 62)
                                    .addComponent(rbP1r2)
                                    .addGap(61, 61, 61)
                                    .addComponent(rbP1r3)
                                    .addGap(68, 68, 68)
                                    .addComponent(lblRes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbP3r1)
                        .addGap(56, 56, 56)
                        .addComponent(rbP3r2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRes3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(46, 46, 46)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagen3)
                        .addGap(42, 42, 42)
                        .addComponent(btnRegresar)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbP1r1)
                                .addComponent(rbP1r2)
                                .addComponent(rbP1r3))
                            .addComponent(lblRes, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbP2r1)
                                .addComponent(rbP2r2)
                                .addComponent(rbP2r3))
                            .addComponent(lblRes2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbP3r2)
                                .addComponent(rbP3r1))
                            .addComponent(lblRes3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void rbP1r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbP1r1ActionPerformed
        rbP1r2.setSelected(false);
        rbP1r3.setSelected(false);
        lblRes.setText("Correcto");
    }//GEN-LAST:event_rbP1r1ActionPerformed

    private void rbP2r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbP2r1ActionPerformed
        rbP2r2.setSelected(false);
        rbP2r3.setSelected(false);
        lblRes2.setText("Correcto");        // TODO add your handling code here:
    }//GEN-LAST:event_rbP2r1ActionPerformed

    private void rbP1r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbP1r2ActionPerformed
        rbP1r1.setSelected(false);
        rbP1r3.setSelected(false);
        lblRes.setText("incorrecto");        // TODO add your handling code here:
    }//GEN-LAST:event_rbP1r2ActionPerformed

    private void rbP1r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbP1r3ActionPerformed
        rbP1r1.setSelected(false);
        rbP1r2.setSelected(false);
        lblRes.setText("Incorrecto");        // TODO add your handling code here:
    }//GEN-LAST:event_rbP1r3ActionPerformed

    private void rbP2r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbP2r2ActionPerformed
        rbP2r1.setSelected(false);
        rbP2r3.setSelected(false);
        lblRes2.setText("Incorrecto");        // TODO add your handling code here:
    }//GEN-LAST:event_rbP2r2ActionPerformed

    private void rbP2r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbP2r3ActionPerformed
        rbP2r1.setSelected(false);
        rbP2r2.setSelected(false);
        lblRes2.setText("Incorrecto");        // TODO add your handling code here:
    }//GEN-LAST:event_rbP2r3ActionPerformed

    private void rbP3r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbP3r1ActionPerformed
        rbP3r2.setSelected(false);
        lblRes3.setText("Correcto");         // TODO add your handling code here:
    }//GEN-LAST:event_rbP3r1ActionPerformed

    private void rbP3r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbP3r2ActionPerformed
       rbP3r1.setSelected(false);
        lblRes3.setText("Incorrecto");  // TODO add your handling code here:
    }//GEN-LAST:event_rbP3r2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel lblRes2;
    private javax.swing.JLabel lblRes3;
    private javax.swing.JRadioButton rbP1r1;
    private javax.swing.JRadioButton rbP1r2;
    private javax.swing.JRadioButton rbP1r3;
    private javax.swing.JRadioButton rbP2r1;
    private javax.swing.JRadioButton rbP2r2;
    private javax.swing.JRadioButton rbP2r3;
    private javax.swing.JRadioButton rbP3r1;
    private javax.swing.JRadioButton rbP3r2;
    private javax.swing.JTextArea txtPregunta1;
    private javax.swing.JTextArea txtPregunta2;
    private javax.swing.JTextArea txtPregunta3;
    // End of variables declaration//GEN-END:variables
}
